~/fabric8-analytics-common/dashboard/repositories/f8a-emr-deployment ~/fabric8-analytics-common/dashboard/repositories/f8a-emr-deployment
created virtual environment CPython3.6.10.final.0-64 in 174ms
  creator CPython3Posix(dest=/home/msawood/fabric8-analytics-common/dashboard/repositories/f8a-emr-deployment/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/msawood/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators PythonActivator,FishActivator,XonshActivator,CShellActivator,PowerShellActivator,BashActivator
Requirement already satisfied: pyflakes in ./venv/lib/python3.6/site-packages (2.2.0)
----------------------------------------------------
Checking source files for common errors in following
directories:
src tests tools
----------------------------------------------------

src/config.py
    Pass
src/__init__.py
    Pass
src/exceptions.py
    Pass
src/api_v1.py
    Pass
src/trained_model_details.py
    Pass
tests/__init__.py
    Pass
tests/conftest.py
    Pass
tests/test_api_v1.py
    Pass
tools/check_python_version.py
    Pass
~/fabric8-analytics-common/dashboard/repositories/f8a-emr-deployment
All checks passed for 9 source files
