~/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-release-monitor ~/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-release-monitor
created virtual environment CPython3.6.10.final.0-64 in 143ms
  creator CPython3Posix(dest=/home/msawood/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-release-monitor/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/msawood/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators PythonActivator,FishActivator,XonshActivator,CShellActivator,PowerShellActivator,BashActivator
Requirement already satisfied: pyflakes in ./venv/lib/python3.6/site-packages (2.2.0)
----------------------------------------------------
Checking source files for common errors in following
directories:
release_monitor
integration_tests
tests
tools
----------------------------------------------------

release_monitor/__init__.py
    Pass
release_monitor/release_monitor.py
    Pass
release_monitor/defaults.py
    Pass
integration_tests/steps/steps.py
    Pass
integration_tests/environment.py
    Pass
tests/__init__.py
    Pass
tests/test_release_monitor.py
    Pass
tools/check_python_version.py
    Pass
----------------------------------------------------
Checking following source files for common errors:
setup.py
run.py
----------------------------------------------------

setup.py
    Pass
run.py
    Pass
~/fabric8-analytics-common/dashboard/repositories/fabric8-analytics-release-monitor
All checks passed for 10 source files
